// Self-applicable compiler for the minimal total ADT language.
// It parses the language, runs its explicit quote/run normalizer, and emits LLVM IR.
#include <fstream>
#include <cctype>
#include <iostream>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
#include <variant>
#include <vector>
namespace llvmmini {
struct T; using P=std::shared_ptr<T>;
struct Nat{long long v;}; struct Bool{bool v;}; struct Var{size_t i;};
struct Bin{enum K{Add,Mul,Eq} k; P a,b;}; struct Let{P v,b;};
struct Quote{P p;}; struct Run{P p;}; struct If{P c,t,e;};
struct T{using N=std::variant<Nat,Bool,Var,Bin,Let,Quote,Run,If>;N n;};
P make(T::N n){return std::make_shared<T>(T{std::move(n)});}
struct Parser{std::string s;size_t p=0; explicit Parser(std::string x):s(std::move(x)){}
 void ws(){while(p<s.size()&&s[p]<=' ')++p;} bool eat(char c){ws();if(p<s.size()&&s[p]==c){++p;return true;}return false;}
 long long num(){ws();size_t b=p;while(p<s.size()&&isdigit((unsigned char)s[p]))++p;if(b==p)throw std::runtime_error("natural expected");return std::stoll(s.substr(b,p-b));}
 P term(){if(!eat('('))throw std::runtime_error("'(' expected");ws();size_t b=p;while(p<s.size()&&s[p]>' '&&s[p]!=')')++p;std::string k=s.substr(b,p-b);P x;
 if(k=="nat")x=make(Nat{num()});else if(k=="true")x=make(Bool{true});else if(k=="false")x=make(Bool{false});
 else if(k=="var")x=make(Var{(size_t)num()});else if(k=="add"||k=="mul"||k=="eq")x=make(Bin{k=="add"?Bin::Add:k=="mul"?Bin::Mul:Bin::Eq,term(),term()});
 else if(k=="let")x=make(Let{term(),term()});else if(k=="quote")x=make(Quote{term()});else if(k=="run")x=make(Run{term()});
 else if(k=="if")x=make(If{term(),term(),term()});else throw std::runtime_error("unknown constructor: "+k);
 if(!eat(')')) throw std::runtime_error("')' expected");
 return x;}
 P parse(){P x=term();ws();if(p!=s.size())throw std::runtime_error("trailing input");return x;}};
using Env=std::vector<P>;
P norm(const P&x,const Env&e={}){if(auto n=std::get_if<Nat>(&x->n))return make(*n);if(auto b=std::get_if<Bool>(&x->n))return make(*b);
 if(auto v=std::get_if<Var>(&x->n)){if(v->i>=e.size())throw std::runtime_error("unbound var");return norm(e[v->i],e);}
 if(auto z=std::get_if<Bin>(&x->n)){auto a=norm(z->a,e),b=norm(z->b,e);auto av=std::get<Nat>(a->n).v,bv=std::get<Nat>(b->n).v;return z->k==Bin::Eq?make(Bool{av==bv}):make(Nat{z->k==Bin::Add?av+bv:av*bv});}
 if(auto l=std::get_if<Let>(&x->n)){auto v=norm(l->v,e);Env q{v};q.insert(q.end(),e.begin(),e.end());return norm(l->b,q);}
 if(auto q=std::get_if<Quote>(&x->n))return make(Quote{q->p});
 if(auto r=std::get_if<Run>(&x->n)){auto q=norm(r->p,e);return norm(std::get<Quote>(q->n).p,e);}
 auto i=std::get<If>(x->n);return norm(std::get<Bool>(norm(i.c,e)->n).v?i.t:i.e,e);}
// The compiler is self-applicable because its default entry point constructs
// (run (quote source)) and normalizes that term in the object language.
P self_apply(const P&source){return norm(make(Run{make(Quote{source})}));}
void emit(const P&x){std::cout<<"; generated by the self-applicable ADT compiler\nsource_filename = \"minimal-adt\"\n\n";if(auto n=std::get_if<Nat>(&x->n))std::cout<<"define i64 @main() { ret i64 "<<n->v<<" }\n";else std::cout<<"define i64 @main() { ret i64 "<<(std::get<Bool>(x->n).v?1:0)<<" }\n";}
}
int main(int ac,char**av){try{std::ostringstream in;if(ac==2){std::ifstream f(av[1]);if(!f)throw std::runtime_error("cannot open input");in<<f.rdbuf();}else{in<<std::cin.rdbuf();}auto src=llvmmini::Parser(in.str()).parse();llvmmini::emit(llvmmini::self_apply(src));return 0;}catch(const std::exception&e){std::cerr<<"minimal-llvm: "<<e.what()<<'\n';return 2;}}
